# Generated by Django 2.0.2 on 2018-03-29 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 10, 56, 44, 632192), verbose_name='start date'),
        ),
    ]
