# Generated by Django 2.0.2 on 2018-03-29 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_test_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 15, 21, 26, 708803), verbose_name='start date'),
        ),
    ]
