# Generated by Django 2.0.2 on 2018-03-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reference_num', models.IntegerField(default=0)),
                ('sub_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disease.SubDisease')),
            ],
        ),
    ]
