# Generated by Django 2.0.2 on 2018-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('pic_url', models.CharField(blank=True, default=None, max_length=500)),
                ('video_url', models.CharField(blank=True, default=None, max_length=1000)),
                ('roles', models.ManyToManyField(to='Navigation.Role')),
            ],
        ),
    ]
