# Generated by Django 2.0.2 on 2018-03-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pic_url',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='video_url',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
